<a href="https://colab.research.google.com/github/sensoumya/myProjects/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (3).csv


In [0]:
import io
df = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_x1 = LabelEncoder()
X[:,1] = le_x1.fit_transform(X[:,1])

In [8]:
le_x2 = LabelEncoder()
X[:,2] = le_x2.fit_transform(X[:,2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
ohe = OneHotEncoder(categorical_features=[1])
X = ohe.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
X = X[:,1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
classifier = Sequential()

In [0]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

In [0]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [0]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [0]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
classifier.fit(X_train,y_train, batch_size=10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4845 - acc: 0.8004
Epoch 2/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4080 - acc: 0.8242
Epoch 3/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.3935 - acc: 0.8264
Epoch 4/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3836 - acc: 0.8287
Epoch 5/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3770 - acc: 0.8374
Epoch 6/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3718 - acc: 0.8454
Epoch 7/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.3679 - acc: 0.8509
Epoch 8/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3648 - acc: 0.8497
Epoch 9/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3626 - acc: 0.8501
Epoch 10/100
8000/8000 [==============================] - 1

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [0]:
from sklearn.metrics import confusion_matrix

In [44]:
cm= confusion_matrix(y_test, y_pred)
cm

array([[1512,   83],
       [ 193,  212]])